import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const map = JSON.parse(await readFile(path.join(root, "scripts/upstream-map.json"), "utf8"));
const imported = map.filter(entry => entry?.status === "imported");
const rows = imported
  .map(entry => `| \`${entry.upstream}\` | \`${entry.target}\` |`)
  .join("\n");
const generated = [
  "# Attribution and scope",
  "",
  "This repository includes adapted pstack materials from the pinned upstream checkout `.upstream/cursor-plugins` at commit `12d587d`. Adaptations replace unavailable host-specific mechanics with OMP APIs and are tracked in `scripts/upstream-map.json`.",
  "",
  "## Imported upstream materials",
  "",
  "The table below is generated by `scripts/build-notice.mjs`; do not edit it by hand.",
  "",
  "| Upstream path | Local target |",
  "|---|---|",
  rows,
  "",
].join("\n");
const noticePath = path.join(root, "NOTICE.md");
if (process.argv.includes("--check")) {
  const current = await readFile(noticePath, "utf8");
  if (current !== generated) {
    console.error("NOTICE.md is stale; run node scripts/build-notice.mjs");
    process.exit(1);
  }
  console.log(`NOTICE.md is current (${imported.length} imported entries).`);
} else {
  await writeFile(noticePath, generated, "utf8");
  console.log(`Wrote NOTICE.md from ${imported.length} imported upstream entries.`);
}
